Repository pagopa/io-dev-api-server, pull requests merged in 2023-11, with the labels that each got.

#315 [IOPID-296] New get nonce handling
  package.json
  src/features/fastLogin/nonceHandler.ts
  src/routers/features/fastLogin/index.ts
Labels: IO-A&I

#317 [IOPID-991] add new openapi configuration
  package.json
  src/payloads/profile.ts
  src/routers/profile.ts
Labels: IO-A&I

#321 [IOPID-1139] Refactored home dashboard & added profile custom configuration for email validation
  README.MD
  assets/html/homeDashboard.html
  assets/html/mail.html
  src/persistence/profile/profile.ts
  src/persistence/profile/userMetadata.ts
  src/routers/configHomeDashboard/configHomeDashboard.ts
  src/routers/profile.ts
  src/routers/public.ts
  src/routers/walletsV2/configDashboard.ts
  src/server.ts
  src/utils/responseTypes.ts
Labels: IO-A&I

#320 chore: [IOBP-408] Added `iowallet://` as custom url schema to provide outcome
  assets/wallet/wallet_onboarding.html
Labels: IO-Bonus & Pagamenti

#323 [IOCOM-686] Add message generation with remote content
  src/config.ts
  src/features/messages/persistence/messagesPayload.ts
  src/features/messages/types/messageTemplate.ts
  src/features/messages/types/messageTemplateWrapper.ts
  src/features/messages/types/messagesConfig.ts
  src/populate-persistence.ts
  src/routers/__tests__/message.test.ts
Labels: IO-Comunicazione
