Repository pagopa/io-dev-api-server, pull requests merged in 2023-09, with the labels that each got.

#294 [IOCOM-437,IOCOM-439,IOCOM-443] Multiple Payments on PN messages
  src/config.ts
  src/features/pn/payloads/messages.ts
  src/features/pn/routers/routers.ts
  src/features/pn/services/services.ts
  src/features/pn/types/notificationPaymentInfo.ts
  src/features/pn/types/notificationRecipient.ts
  src/payloads/backend.ts
  src/payloads/message.ts
  src/payloads/response.ts
  src/persistence/payments.ts
  src/persistence/services.ts
  src/populate-persistence.ts
  src/routers/__tests__/message.test.ts
  src/routers/features/siciliaVola/secured/index.ts
  src/routers/message.ts
  src/routers/payment.ts
  src/routers/services_metadata.ts
  src/routers/walletsV2/configDashboard.ts
  src/routers/walletsV2/methods/cobadge.ts
  src/server.ts
  src/types/PaymentStatus.ts
  src/types/config.ts
  src/utils/array.ts
  src/utils/payment.ts
  src/utils/validator.ts
Labels: IO-Comunicazione

#295 [IOCOM-500] Support for cancelled SEND message
  src/features/pn/payloads/messages.ts
  src/features/pn/types/notificationStatusHistoryElement.ts
  src/persistence/payments.ts
  src/routers/payment.ts
  src/types/config.ts
  src/utils/payment.ts
Labels: IO-Comunicazione

#296 [IOCOM-444] Sample F24 data for SEND messages
  assets/messages/pn/attachments/loremIpsum.pdf
  assets/messages/pn/f24/f2400.pdf
  assets/messages/pn/f24/f2401.pdf
  assets/messages/pn/f24/f2402.pdf
  assets/messages/pn/f24/f2403.pdf
  assets/messages/pn/f24/f2404.pdf
  assets/messages/pn/f24/f2405.pdf
  assets/messages/pn/f24/f2406.pdf
  assets/messages/pn/f24/f2407.pdf
  assets/messages/pn/f24/f2408.pdf
  assets/messages/pn/f24/f2409.pdf
Labels: IO-Comunicazione

#297 chore: [IOPID-714,IOPID-670]: Discriminate currentProfile based on auth provider
  src/features/pn/payloads/messages.ts
  src/payloads/profile.ts
  src/payloads/wallet_v2.ts
  src/persistence/sessionInfo.ts
  src/routers/profile.ts
  src/routers/public.ts
Labels: IO-A&I

#301 [chore] PN configuration disabled by default
  src/config.ts
  src/routers/__tests__/message.test.ts
Labels: IO-Comunicazione

#303 [IOCOM-501] Add support for `dueDate`
  package.json
  src/persistence/payments.ts
Labels: IO-Comunicazione

#304 [IO-558] Add recipientType in the NotificationRecipient payload
  src/features/pn/payloads/messages.ts
  src/features/pn/types/notificationRecipient.ts
Labels: IO-Comunicazione

#302 [IOBP-262] Add IdPay code routes
  package.json
  src/payloads/features/idpay/get-wallet-detail.ts
  src/persistence/idpay.ts
  src/routers/features/idpay/__tests__/wallet.test.ts
  src/routers/features/idpay/timeline.ts
  src/routers/features/idpay/wallet.ts
Labels: IO-Bonus & Pagamenti

#306 [IOCOM-563] Payment completion tracking through payments' database
  src/payloads/message.ts
  src/routers/payment.ts
Labels: IO-Comunicazione
