Repository pagopa/io-dev-api-server, pull requests merged in 2023-12, with the labels that each got.

#329 [IOPID-1181] Add email uniqueness verification FF
  package.json
  src/payloads/backend.ts
Labels: IO-A&I

#324 chore: [IOBP-421] Added additional outcome to handle already onboarded method
  assets/wallet/wallet_onboarding.html
Labels: IO-Bonus & Pagamenti

#331 chore: [IOBP-451] Add update wallet services API
  package.json
  src/features/wallet/persistence/userWallet.ts
  src/features/wallet/routers/wallets.ts
Labels: IO-Bonus & Pagamenti

#332 [IOCOM-739] Add the `has_remote_content` property to messages with remote content
  package.json
  src/features/messages/persistence/messagesPayload.ts
Labels: IO-Comunicazione

#333 chore: set user email as not mandatory
  src/types/config.ts
Labels: IO-A&I

#334 [IOCOM-740] Update config.ts with new ToS version
  src/config.ts
Labels: IO-Comunicazione

#325 [IOBP-432] Add wallet payment authorization WebView
  assets/wallet/wallet_payment.html
Labels: IO-Bonus & Pagamenti
