Repository pagopa/io-dev-api-server, pull requests merged in 2024-02, with the labels that each got.

#345 [IOPID-1448] chore: add 409 management
  src/persistence/profile/profile.ts
  src/routers/__tests__/profile.test.ts
Labels: IO-A&I

#349 [IOCOM-1091] Add a message endpoint to create a new message
  assets/html/homeDashboard.html
  assets/html/messages.html
  src/config.ts
  src/features/messages/persistence/messagesDatabase.ts
  src/features/messages/routers/messagesRouter.ts
  src/features/messages/services/messagesService.ts
Labels: IO-Comunicazione

#350 chore: [IOBP-552] Added additional outcome into html page for BPay onboarding
  assets/wallet/wallet_onboarding.html
Labels: IO-Bonus & Pagamenti
