Repository pagopa/io-dev-api-server, pull requests merged in 2024-11, with the labels that each got.

#431 [IOCOM-1885] Autogenerated FIMS authentication specs
  package.json
  src/features/fims/routers/providerRouter.ts
  src/features/fims/services/providerService.ts
  src/features/fims/types/authentication.ts
  src/features/fims/types/relyingParty.ts
  yarn.lock
Labels: IO-Comunicazione

#433 [IOPID-2406] add logic trigger errorMessage and not only the errorCode in login flow
  assets/html/login.html
  src/payloads/login.ts
  src/routers/public.ts
Labels: IO-A&I

#435 [IOCOM-1886] Autogenerated FIMS history specs
  package.json
  src/features/fims/routers/historyRouter.ts
  src/features/fims/services/historyService.ts
  src/features/fims/types/history.ts
  src/features/fims/types/lastExportRequest.ts
Labels: IO-Comunicazione

#438 chore: [IOBP-982] Add outcome 99 into mock webview payment page
  assets/wallet/wallet_payment.html
Labels: IO-Bonus & Pagamenti

#440 [IOPID-2137] Update definitions
  assets/yaml/content.yaml
  package.json
  src/payloads/backend.ts
Labels: IO-A&I

#441 chore: [IOBP-981] Add `PSP_ERROR` outcome into payment flow webpage
  assets/wallet/wallet_payment.html
Labels: IO-Bonus & Pagamenti
