Repository pagopa/io-dev-api-server, pull requests merged in 2024-01, with the labels that each got.

#336 [IOPID-1301] - Bump ToS version from 4.7 a 4.8
  src/config.ts
Labels: dont-merge ✋🏼, IO-A&I

#338 Revert "Revert "[IOPID-1301] - Bump ToS version from 4.7 a 4.8""
  src/config.ts
Labels: IO-A&I

#339 [IOCOM-923] Remove medical prescription
  assets/messages/barcodeReceipt.svg
  src/config.ts
  src/features/messages/persistence/messagesPayload.ts
  src/features/messages/types/messagesConfig.ts
  src/features/pn/payloads/messages.ts
  src/populate-persistence.ts
  src/routers/__tests__/message.test.ts
Labels: IO-Comunicazione

#344 [IOPID-1374] Update content specs definitions
  package.json
  src/payloads/backend.ts
Labels: IO-A&I
