Repository pagopa/io-dev-api-server, pull requests merged in 2024-10, with the labels that each got.

#416 chore: [IOBP-909] Adapt IDPay definitions mock API
  package.json
  src/payloads/features/idpay/get-timeline-detail.ts
  src/persistence/idpay.ts
  src/routers/features/idpay/payment.ts
Labels: IO-Bonus & Pagamenti

#413 [IOPID-2306] bump tos version from 4.9 a 4.91
  src/config.ts
  src/payloads/backend.ts
Labels: IO-A&I

#421 chore: [IOBP-921] Added missing outcome into payments dropdown webview
  assets/wallet/wallet_payment.html
Labels: IO-Bonus & Pagamenti

#422 [IOCOM-1758] addition of multiBanner setup to io-dev-server
  package.json
  src/payloads/backend.ts
Labels: IO-Comunicazione

#389 chore: [IOBP-697] Add payments section definitions
  src/payloads/backend.ts
Labels: IO-Bonus & Pagamenti

#423 chore: [IOBP-927] Adapt new openAPI biz-events
  package.json
  src/features/payments/persistence/notices.ts
  src/features/payments/persistence/transactions.ts
  src/features/payments/routers/index.ts
  src/features/payments/routers/notices.ts
  src/features/payments/routers/payment.ts
  src/features/payments/routers/router.ts
  src/features/payments/utils/transactions.ts
Labels: IO-Bonus & Pagamenti

#417 [IOPID-2093] Parameterisation of getSession endpoint
  src/payloads/session.ts
  src/routers/session.ts
Labels: IO-A&I

#402 chore: [IOBP-804] Added feedback banner mock for the new payment success screen
  package.json
  src/payloads/backend.ts
Labels: IO-Bonus & Pagamenti

#428 multibanner payload update
  src/payloads/backend.ts
Labels: IO-Comunicazione

#425 [IOPID-2359] remove remote FF session refresh
  package.json
  src/payloads/backend.ts
Labels: IO-A&I

#430 feat: [IOBP-838] Remove receipt from list endpoint
  src/config.ts
  src/features/payments/routers/notices.ts
  src/types/config.ts
Labels: IO-Bonus & Pagamenti
