Repository pagopa/io-dev-api-server, pull requests merged in 2024-05, with the labels that each got.

#371 [IOPID-1742] change CDN urls
  assets/bonus_available/bonus_available_v2.json
  src/payloads/backend.ts
  src/payloads/wallet.ts
Labels: help wanted

#374 fix: SPID logo retrieval
  assets/spid/idps/spid-idp-etnaid.png
  assets/spid/idps/spid-idp-infocamereid.png
  assets/spid/idps/spid-idp-intesigroupspid.png
  assets/spid/idps/spid-idp-teamsystemid.png
  src/routers/services_metadata.ts
Labels: IO-A&I

#375 [IOPID-1826] Change IdPs commercial name
  assets/spid/idps/list.json
Labels: IO-A&I

#372 [IOPAE-1118] Add institution's services endpoint
  src/config.ts
  src/features/services/payloads/get-featured-items.ts
  src/features/services/payloads/get-institutions.ts
  src/features/services/payloads/get-services.ts
  src/features/services/routers/institutions.ts
  src/features/services/types/configuration.ts
Labels: IO-Enti & Servizi

#376 [IOPAE-1141] Add featured institutions and services APIs mock
  src/config.ts
  src/features/services/payloads/get-featured-institutions.ts
  src/features/services/payloads/get-featured-items.ts
  src/features/services/payloads/get-featured-services.ts
  src/features/services/routers/featured.ts
  src/features/services/routers/index.ts
  src/features/services/routers/institutions.ts
  src/features/services/routers/services.ts
  src/features/services/types/configuration.ts
Labels: IO-Enti & Servizi

#380 chore: Show error numbers in `login.html`
  assets/html/login.html
Labels: IO-A&I

#369 feat: [IOBP-609] Add Biz Events transactions routes
  assets/wallet/wallet_payment.html
  package.json
  src/config.ts
  src/features/payments/index.ts
  src/features/payments/payloads/paymentMethods.ts
  src/features/payments/payloads/payments.ts
  src/features/payments/payloads/transactions.ts
  src/features/payments/persistence/paymentMethods.ts
  src/features/payments/persistence/transactions.ts
  src/features/payments/persistence/userWallet.ts
  src/features/payments/routers/index.ts
  src/features/payments/routers/payment.ts
  src/features/payments/routers/router.ts
  src/features/payments/routers/transactions.ts
  src/features/payments/routers/wallets.ts
  src/features/payments/types/configuration.ts
  src/features/payments/types/failure.ts
  src/features/payments/utils/onboarding.ts
  src/features/payments/utils/payment.ts
  src/features/payments/utils/transactions.ts
  src/routers/public.ts
  src/routers/wallet.ts
  src/server.ts
  src/types/config.ts
Labels: IO-Bonus & Pagamenti

#379 chore: [IOBP-651] Upgraded ecommerce & walletv3 definitions
  package.json
  src/features/payments/persistence/userWallet.ts
Labels: IO-Bonus & Pagamenti

#382 feat: [IOBP-652,IOBP-656] Add biz-events transaction download pdf
  assets/payments/receipts/loremIpsum.pdf
  src/features/payments/routers/transactions.ts
Labels: IO-Bonus & Pagamenti

#383 chore: [IOBP-660] Add remote feature flag to the new payment section
  package.json
  src/payloads/backend.ts
Labels: IO-Bonus & Pagamenti

#377 [IOPAE-1147] Fix `/institutions` endpoint
  src/features/services/payloads/get-institutions.ts
Labels: IO-Enti & Servizi
