Repository pagopa/io-dev-api-server, pull requests merged in 2025-02, with the labels that each got.

#458 feat(IDPay): [IOBP-1131] input text for onboarding
  package.json
  src/payloads/features/idpay/check-prerequisites.ts
  src/payloads/features/idpay/get-initiative-data.ts
  src/payloads/features/idpay/types.ts
Labels: IO-Bonus & Pagamenti

#457 chore: [IOBP-1143] add mock idpay expense type
  src/config.ts
  src/persistence/idpay.ts
  src/types/config.ts
Labels: IO-Bonus & Pagamenti

#463 chore: [IOBP-1137] Mock webviewUrl with FIMS url into IDPay expense initiative
  src/persistence/idpay.ts
Labels: IO-Bonus & Pagamenti

#466 [IOPID-2720] FAQ Banner educational for Zendesk subcategories
  assets/assistanceTools/zendesk.json
  scripts/generate-api-models.sh
Labels: dont-merge ✋🏼, IO-A&I

#467 [IOPID-2719] FastLogin expiration date
  scripts/generate-api-models.sh
  src/payloads/backend.ts
  src/payloads/session.ts
Labels: IO-A&I

#469 [IOCOM-2086] addition of SEND banner to payload
  src/payloads/backend.ts
Labels: IO-Comunicazione
