Repository pagopa/io-dev-api-server, pull requests merged in 2025-06, with the labels that each got.

#487 chore: [IOBP-1727] Add CdC FIMS mock config
  scripts/generate-api-models.sh
  src/payloads/backend.ts
Labels: IO-Bonus & Pagamenti

#485 feat: [IOCOM-2302] eCommerce API for payments on messages
  assets/wallet/wallet_payment.html
  scripts/generate-api-models.sh
  src/config.ts
  src/features/messages/routers/messagesRouter.ts
  src/features/payments/routers/payment.ts
  src/features/payments/types/failure.ts
  src/routers/__tests__/paypal.test.ts
  src/routers/payment.ts
  src/routers/walletsV3/methods/paypal.ts
  src/server.ts
  src/types/config.ts
Labels: IO-Comunicazione

#486 test: [IOBP-661] Add payments & notices mock unit tests
  src/features/payments/persistence/__tests__/notices.test.ts
  src/features/payments/persistence/__tests__/paymentMethods.test.ts
  src/features/payments/persistence/__tests__/userWallet.test.ts
  src/features/payments/persistence/notices.ts
Labels: IO-Bonus & Pagamenti

#489 fix: [IOCOM-2302] Fix bad conversion for dueDate in paymentData
  src/persistence/payments.ts
Labels: IO-Comunicazione

#493 fix: [IOCOM-2302] Ongoing mapped to KO_RETRIABLE
  assets/wallet/wallet_payment.html
  src/features/payments/routers/payment.ts
Labels: IO-Comunicazione

#490 chore: [IOBP-1748] Add mock to FIMS to disable iOS sharing cookie
  scripts/generate-api-models.sh
  src/config.ts
  src/payloads/backend.ts
Labels: IO-Comunicazione, IO-Bonus & Pagamenti

#495 feature: [IOCOM-2419] Production messages in the dev-server
  package.json
  src/config.ts
  src/features/messages/persistence/messagesDatabase.ts
  src/features/messages/routers/productionCrawlerRouter.ts
  src/features/messages/types/messagesConfig.ts
  src/populate-persistence.ts
  src/server.ts
  yarn.lock
Labels: IO-Comunicazione
