Repository pagopa/io-dev-api-server, pull requests merged in 2025-01, with the labels that each got.

#454 chore: [IOPID-2580] add management of remote portal urls
  assets/yaml/content.yaml
  package.json
  src/payloads/backend.ts
Labels: IO-A&I

#456 chore: [IOBP-1140] Add onUs mocked field on PSP list
  src/features/payments/payloads/transactions.ts
Labels: IO-Bonus & Pagamenti

#459 [IOCOM-2071] Remote configuration for IOMarkdown
  assets/CdcSwagger.yml
  package.json
  src/payloads/backend.ts
Labels: IO-Comunicazione

#460 chore: [PE-786] CGN update api version
  package.json
Labels: IO-Bonus & Pagamenti

#462 fix: [IOBP-1167] Random IDPay test fails
  src/routers/features/idpay/__tests__/payment.test.ts
Labels: IO-Bonus & Pagamenti
