Repository pagopa/io-dev-api-server, pull requests merged in 2025-09, with the labels that each got.

#519 feat: [IOCOM-2556] Remove ToS from SEND
  src/config.ts
  src/features/messages/routers/ioSendRouter.ts
  src/features/messages/services/ioSendService.ts
  src/features/pn/models/AAR.ts
  src/features/pn/repositories/aarRepository.ts
  src/features/pn/routers/aarRouter.ts
  src/features/pn/services/aarService.ts
  src/features/pn/types/sendConfig.ts
Labels: IO-Comunicazione

#521 feat: [IOCOM-2543] feature AAR min version
  scripts/generate-api-models.sh
  src/payloads/backend.ts
Labels: IO-Comunicazione

#527 [IOCOM-2575] updated AAR QR code RegEx
  src/payloads/backend.ts
Labels: IO-Comunicazione

#530 [IOCOM-2544] AAR Regex update
  src/payloads/backend.ts
Labels: IO-Comunicazione

#531 fix: [IOCOM-2585] Fix for `x-pagopa-pn-io-src` header and 403 on AAR QRCode not belonging to user
  src/features/messages/services/ioSendService.ts
  src/features/pn/services/aarService.ts
Labels: IO-Comunicazione

#533 feat: [IOBP-1985] Add user onboarded initiative list statuses API
  src/payloads/features/idpay/check-prerequisites.ts
  src/payloads/features/idpay/get-initiative-data.ts
  src/payloads/features/idpay/get-onboarding-initiative-user-status.ts
  src/payloads/features/idpay/types.ts
  src/persistence/idpay.ts
  src/routers/features/idpay/onboarding.ts
Labels: IO-Bonus & Pagamenti

#536 chore [IOPID-3332]: change error code name
  assets/html/login.html
Labels: IO-A&I

#543 chore: [IOBP-2033] CdC FAQ
  assets/bonus_available/bonus_available_v2.json
  assets/contextual_help/data.json
Labels: IO-Bonus & Pagamenti
